sign-commit = true

pre-release-commit-message = "Version {{version}}"
post-release-commit-message = "Starting next development version {{next_version}}"
tag-message = "{{crate_name}} version {{version}}"

pre-release-replacements = [
  {file="README.md", search="sbanken = .*", replace="sbanken = \"{{version}}\""},
  {file="README.md", search="- Package version: .*", replace="- Package version: {{version}}"},
]
