/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Account {
    /// The account identifier for use with other APIs that require AccountID.
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The account's public account number
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    /// The customerId of the person that owns the account, may be different from the queried customerId.
    #[serde(rename = "ownerCustomerId", skip_serializing_if = "Option::is_none")]
    pub owner_customer_id: Option<String>,
    /// The name of the account. Not unique.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The type of the account. Descriptive.
    #[serde(rename = "accountType", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<String>,
    /// The amount currently available on the account. This is the money available to spend. It will differ from the account balance, typically by credit limit and by pending transactions.
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<f32>,
    /// The current account balance. This is the money owned.
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<f32>,
    /// The current credit limit on the account.
    #[serde(rename = "creditLimit", skip_serializing_if = "Option::is_none")]
    pub credit_limit: Option<f32>,
}

impl Account {
    pub fn new() -> Account {
        Account {
            account_id: None,
            account_number: None,
            owner_customer_id: None,
            name: None,
            account_type: None,
            available: None,
            balance: None,
            credit_limit: None,
        }
    }
}


