/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountProductCodeV1 {
    #[serde(rename = "AieHighInterest")]
    AieHighInterest,
    #[serde(rename = "AieStandard")]
    AieStandard,
    #[serde(rename = "AieMortgageCredit")]
    AieMortgageCredit,
    #[serde(rename = "AieBsu")]
    AieBsu,
    #[serde(rename = "Creditcard")]
    Creditcard,
    #[serde(rename = "StockTradingWithoutCredit")]
    StockTradingWithoutCredit,
    #[serde(rename = "StockTradingWithCredit")]
    StockTradingWithCredit,
    #[serde(rename = "Mortgage")]
    Mortgage,
    #[serde(rename = "CarLoan")]
    CarLoan,
    #[serde(rename = "ConsumerLoan")]
    ConsumerLoan,
    #[serde(rename = "DebtSecuritesLoan")]
    DebtSecuritesLoan,
    #[serde(rename = "Undefined")]
    Undefined,

}

impl ToString for AccountProductCodeV1 {
    fn to_string(&self) -> String {
        match self {
            Self::AieHighInterest => String::from("AieHighInterest"),
            Self::AieStandard => String::from("AieStandard"),
            Self::AieMortgageCredit => String::from("AieMortgageCredit"),
            Self::AieBsu => String::from("AieBsu"),
            Self::Creditcard => String::from("Creditcard"),
            Self::StockTradingWithoutCredit => String::from("StockTradingWithoutCredit"),
            Self::StockTradingWithCredit => String::from("StockTradingWithCredit"),
            Self::Mortgage => String::from("Mortgage"),
            Self::CarLoan => String::from("CarLoan"),
            Self::ConsumerLoan => String::from("ConsumerLoan"),
            Self::DebtSecuritesLoan => String::from("DebtSecuritesLoan"),
            Self::Undefined => String::from("Undefined"),
        }
    }
}




