/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum AccountProductCodeV1 {
    #[serde(rename = "AieHighInterest")]
    AieHighInterest,
    #[serde(rename = "AieStandard")]
    AieStandard,
    #[serde(rename = "AieMortgageCredit")]
    AieMortgageCredit,
    #[serde(rename = "AieBsu")]
    AieBsu,
    #[serde(rename = "Creditcard")]
    Creditcard,
    #[serde(rename = "StockTradingWithoutCredit")]
    StockTradingWithoutCredit,
    #[serde(rename = "StockTradingWithCredit")]
    StockTradingWithCredit,
    #[serde(rename = "Mortgage")]
    Mortgage,
    #[serde(rename = "CarLoan")]
    CarLoan,
    #[serde(rename = "ConsumerLoan")]
    ConsumerLoan,
    #[serde(rename = "DebtSecuritesLoan")]
    DebtSecuritesLoan,
    #[serde(rename = "Undefined")]
    Undefined,

}

impl std::string::ToString for AccountProductCodeV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::AieHighInterest => "AieHighInterest".to_string(),
        
            Self::AieStandard => "AieStandard".to_string(),
        
            Self::AieMortgageCredit => "AieMortgageCredit".to_string(),
        
            Self::AieBsu => "AieBsu".to_string(),
        
            Self::Creditcard => "Creditcard".to_string(),
        
            Self::StockTradingWithoutCredit => "StockTradingWithoutCredit".to_string(),
        
            Self::StockTradingWithCredit => "StockTradingWithCredit".to_string(),
        
            Self::Mortgage => "Mortgage".to_string(),
        
            Self::CarLoan => "CarLoan".to_string(),
        
            Self::ConsumerLoan => "ConsumerLoan".to_string(),
        
            Self::DebtSecuritesLoan => "DebtSecuritesLoan".to_string(),
        
            Self::Undefined => "Undefined".to_string(),
        
        }
    }
}





