/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum AccountStatusCodeV1 {
    #[serde(rename = "ActiveAccount")]
    ActiveAccount,
    #[serde(rename = "Blocked")]
    Blocked,
    #[serde(rename = "BlockedDeposit")]
    BlockedDeposit,
    #[serde(rename = "BlockedWithdrawel")]
    BlockedWithdrawel,
    #[serde(rename = "Closed")]
    Closed,
    #[serde(rename = "Undefined")]
    Undefined,

}

impl std::string::ToString for AccountStatusCodeV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::ActiveAccount => "ActiveAccount".to_string(),
        
            Self::Blocked => "Blocked".to_string(),
        
            Self::BlockedDeposit => "BlockedDeposit".to_string(),
        
            Self::BlockedWithdrawel => "BlockedWithdrawel".to_string(),
        
            Self::Closed => "Closed".to_string(),
        
            Self::Undefined => "Undefined".to_string(),
        
        }
    }
}





