/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Card {
    #[serde(rename = "cardId", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<String>,
    #[serde(rename = "cardNumber", skip_serializing_if = "Option::is_none")]
    pub card_number: Option<String>,
    #[serde(rename = "cardVersionNumber")]
    pub card_version_number: i32,
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "expiryDate")]
    pub expiry_date: String,
    #[serde(rename = "accountOwner", skip_serializing_if = "Option::is_none")]
    pub account_owner: Option<String>,
    #[serde(rename = "status")]
    pub status: crate::models::CardStatus,
    #[serde(rename = "cardType", skip_serializing_if = "Option::is_none")]
    pub card_type: Option<String>,
    #[serde(rename = "productCode")]
    pub product_code: crate::models::ProductCode,
}

impl Card {
    pub fn new(card_version_number: i32, expiry_date: String, status: crate::models::CardStatus, product_code: crate::models::ProductCode) -> Card {
        Card {
            card_id: None,
            card_number: None,
            card_version_number,
            account_number: None,
            customer_id: None,
            expiry_date,
            account_owner: None,
            status,
            card_type: None,
            product_code,
        }
    }
}


