/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CardDetailsV1 {
    #[serde(rename = "cardNumber", skip_serializing_if = "Option::is_none")]
    pub card_number: Option<String>,
    #[serde(rename = "currencyAmount", skip_serializing_if = "Option::is_none")]
    pub currency_amount: Option<f64>,
    #[serde(rename = "currencyRate", skip_serializing_if = "Option::is_none")]
    pub currency_rate: Option<f64>,
    #[serde(rename = "merchantCategoryCode", skip_serializing_if = "Option::is_none")]
    pub merchant_category_code: Option<String>,
    #[serde(rename = "merchantCategoryDescription", skip_serializing_if = "Option::is_none")]
    pub merchant_category_description: Option<String>,
    #[serde(rename = "merchantCity", skip_serializing_if = "Option::is_none")]
    pub merchant_city: Option<String>,
    #[serde(rename = "merchantName", skip_serializing_if = "Option::is_none")]
    pub merchant_name: Option<String>,
    #[serde(rename = "originalCurrencyCode", skip_serializing_if = "Option::is_none")]
    pub original_currency_code: Option<String>,
    #[serde(rename = "purchaseDate", skip_serializing_if = "Option::is_none")]
    pub purchase_date: Option<String>,
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
}

impl CardDetailsV1 {
    pub fn new() -> CardDetailsV1 {
        CardDetailsV1 {
            card_number: None,
            currency_amount: None,
            currency_rate: None,
            merchant_category_code: None,
            merchant_category_description: None,
            merchant_city: None,
            merchant_name: None,
            original_currency_code: None,
            purchase_date: None,
            transaction_id: None,
        }
    }
}


