/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum CardStatusV1 {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "Renewal")]
    Renewal,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Blocked")]
    Blocked,

}

impl std::string::ToString for CardStatusV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::Unknown => "Unknown".to_string(),
        
            Self::Active => "Active".to_string(),
        
            Self::Inactive => "Inactive".to_string(),
        
            Self::Renewal => "Renewal".to_string(),
        
            Self::Deleted => "Deleted".to_string(),
        
            Self::Blocked => "Blocked".to_string(),
        
        }
    }
}





