/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardDetails {
    #[serde(rename = "cardNumber", skip_serializing_if = "Option::is_none")]
    pub card_number: Option<String>,
    #[serde(rename = "currencyAmount")]
    pub currency_amount: f32,
    #[serde(rename = "currencyRate")]
    pub currency_rate: f32,
    #[serde(rename = "merchantCategoryCode", skip_serializing_if = "Option::is_none")]
    pub merchant_category_code: Option<String>,
    #[serde(rename = "merchantCategoryDescription", skip_serializing_if = "Option::is_none")]
    pub merchant_category_description: Option<String>,
    #[serde(rename = "merchantCity", skip_serializing_if = "Option::is_none")]
    pub merchant_city: Option<String>,
    #[serde(rename = "merchantName", skip_serializing_if = "Option::is_none")]
    pub merchant_name: Option<String>,
    #[serde(rename = "originalCurrencyCode", skip_serializing_if = "Option::is_none")]
    pub original_currency_code: Option<String>,
    #[serde(rename = "purchaseDate")]
    pub purchase_date: String,
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
}

impl CardDetails {
    pub fn new(currency_amount: f32, currency_rate: f32, purchase_date: String) -> CardDetails {
        CardDetails {
            card_number: None,
            currency_amount,
            currency_rate,
            merchant_category_code: None,
            merchant_category_description: None,
            merchant_city: None,
            merchant_name: None,
            original_currency_code: None,
            purchase_date,
            transaction_id: None,
        }
    }
}


