/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CardV1 {
    #[serde(rename = "cardId", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<String>,
    #[serde(rename = "cardNumber", skip_serializing_if = "Option::is_none")]
    pub card_number: Option<String>,
    #[serde(rename = "cardVersionNumber", skip_serializing_if = "Option::is_none")]
    pub card_version_number: Option<i32>,
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "expiryDate", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<String>,
    #[serde(rename = "accountOwner", skip_serializing_if = "Option::is_none")]
    pub account_owner: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::CardStatusV1>,
    #[serde(rename = "cardType", skip_serializing_if = "Option::is_none")]
    pub card_type: Option<String>,
    #[serde(rename = "productCode", skip_serializing_if = "Option::is_none")]
    pub product_code: Option<crate::models::ProductCodeV1>,
}

impl CardV1 {
    pub fn new() -> CardV1 {
        CardV1 {
            card_id: None,
            card_number: None,
            card_version_number: None,
            account_number: None,
            customer_id: None,
            expiry_date: None,
            account_owner: None,
            status: None,
            card_type: None,
            product_code: None,
        }
    }
}


