/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EFakturaPayRequest {
    #[serde(rename = "eFakturaId", skip_serializing_if = "Option::is_none")]
    pub e_faktura_id: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "payOnlyMinimumAmount")]
    pub pay_only_minimum_amount: bool,
}

impl EFakturaPayRequest {
    pub fn new(pay_only_minimum_amount: bool) -> EFakturaPayRequest {
        EFakturaPayRequest {
            e_faktura_id: None,
            account_id: None,
            pay_only_minimum_amount,
        }
    }
}


