/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum EducationLevelV1 {
    #[serde(rename = "ElementarySchool")]
    ElementarySchool,
    #[serde(rename = "HighSchool")]
    HighSchool,
    #[serde(rename = "HigherEducationUpTo3Years")]
    HigherEducationUpTo3Years,
    #[serde(rename = "HigherEducation3To5Years")]
    HigherEducation3To5Years,
    #[serde(rename = "HigherEducationMoreThan5Years")]
    HigherEducationMoreThan5Years,

}

impl std::string::ToString for EducationLevelV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::ElementarySchool => "ElementarySchool".to_string(),
        
            Self::HighSchool => "HighSchool".to_string(),
        
            Self::HigherEducationUpTo3Years => "HigherEducationUpTo3Years".to_string(),
        
            Self::HigherEducation3To5Years => "HigherEducation3To5Years".to_string(),
        
            Self::HigherEducationMoreThan5Years => "HigherEducationMoreThan5Years".to_string(),
        
        }
    }
}





