/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EducationLevelV1 {
    #[serde(rename = "ElementarySchool")]
    ElementarySchool,
    #[serde(rename = "HighSchool")]
    HighSchool,
    #[serde(rename = "HigherEducationUpTo3Years")]
    HigherEducationUpTo3Years,
    #[serde(rename = "HigherEducation3To5Years")]
    HigherEducation3To5Years,
    #[serde(rename = "HigherEducationMoreThan5Years")]
    HigherEducationMoreThan5Years,

}

impl ToString for EducationLevelV1 {
    fn to_string(&self) -> String {
        match self {
            Self::ElementarySchool => String::from("ElementarySchool"),
            Self::HighSchool => String::from("HighSchool"),
            Self::HigherEducationUpTo3Years => String::from("HigherEducationUpTo3Years"),
            Self::HigherEducation3To5Years => String::from("HigherEducation3To5Years"),
            Self::HigherEducationMoreThan5Years => String::from("HigherEducationMoreThan5Years"),
        }
    }
}




