/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorType {
    #[serde(rename = "System")]
    System,
    #[serde(rename = "Input")]
    Input,
    #[serde(rename = "State")]
    State,
    #[serde(rename = "ServiceUnavailable")]
    ServiceUnavailable,
    #[serde(rename = "CustomHttpStatus")]
    CustomHttpStatus,
    #[serde(rename = "NotFound")]
    NotFound,

}

impl ToString for ErrorType {
    fn to_string(&self) -> String {
        match self {
            Self::System => String::from("System"),
            Self::Input => String::from("Input"),
            Self::State => String::from("State"),
            Self::ServiceUnavailable => String::from("ServiceUnavailable"),
            Self::CustomHttpStatus => String::from("CustomHttpStatus"),
            Self::NotFound => String::from("NotFound"),
        }
    }
}




