/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum ErrorType {
    #[serde(rename = "System")]
    System,
    #[serde(rename = "Input")]
    Input,
    #[serde(rename = "State")]
    State,
    #[serde(rename = "ServiceUnavailable")]
    ServiceUnavailable,
    #[serde(rename = "CustomHttpStatus")]
    CustomHttpStatus,
    #[serde(rename = "NotFound")]
    NotFound,

}

impl std::string::ToString for ErrorType {
    fn to_string(&self) -> String {
        match self {
        
            Self::System => "System".to_string(),
        
            Self::Input => "Input".to_string(),
        
            Self::State => "State".to_string(),
        
            Self::ServiceUnavailable => "ServiceUnavailable".to_string(),
        
            Self::CustomHttpStatus => "CustomHttpStatus".to_string(),
        
            Self::NotFound => "NotFound".to_string(),
        
        }
    }
}





