/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum HomeTypeV1 {
    #[serde(rename = "SelfOwnership")]
    SelfOwnership,
    #[serde(rename = "HousingCooperative")]
    HousingCooperative,
    #[serde(rename = "Renting")]
    Renting,
    #[serde(rename = "AtParents")]
    AtParents,

}

impl std::string::ToString for HomeTypeV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::SelfOwnership => "SelfOwnership".to_string(),
        
            Self::HousingCooperative => "HousingCooperative".to_string(),
        
            Self::Renting => "Renting".to_string(),
        
            Self::AtParents => "AtParents".to_string(),
        
        }
    }
}





