/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HomeTypeV1 {
    #[serde(rename = "SelfOwnership")]
    SelfOwnership,
    #[serde(rename = "HousingCooperative")]
    HousingCooperative,
    #[serde(rename = "Renting")]
    Renting,
    #[serde(rename = "AtParents")]
    AtParents,

}

impl ToString for HomeTypeV1 {
    fn to_string(&self) -> String {
        match self {
            Self::SelfOwnership => String::from("SelfOwnership"),
            Self::HousingCooperative => String::from("HousingCooperative"),
            Self::Renting => String::from("Renting"),
            Self::AtParents => String::from("AtParents"),
        }
    }
}




