/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LoanAccountV1 {
    #[serde(rename = "availableAmount", skip_serializing_if = "Option::is_none")]
    pub available_amount: Option<f64>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<f64>,
    #[serde(rename = "negatedBalance", skip_serializing_if = "Option::is_none")]
    pub negated_balance: Option<f64>,
    #[serde(rename = "grantedAmount", skip_serializing_if = "Option::is_none")]
    pub granted_amount: Option<f64>,
    #[serde(rename = "isPaymentFromThisAccountAllowed", skip_serializing_if = "Option::is_none")]
    pub is_payment_from_this_account_allowed: Option<bool>,
    #[serde(rename = "isStandingOrderFromThisAccountAllowed", skip_serializing_if = "Option::is_none")]
    pub is_standing_order_from_this_account_allowed: Option<bool>,
    #[serde(rename = "isThisAccountAccessible", skip_serializing_if = "Option::is_none")]
    pub is_this_account_accessible: Option<bool>,
    #[serde(rename = "isTransferFromThisAccountAllowed", skip_serializing_if = "Option::is_none")]
    pub is_transfer_from_this_account_allowed: Option<bool>,
    #[serde(rename = "isTransferToThisAccountAllowed", skip_serializing_if = "Option::is_none")]
    pub is_transfer_to_this_account_allowed: Option<bool>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "accountProduct", skip_serializing_if = "Option::is_none")]
    pub account_product: Option<Box<crate::models::AccountProductV1>>,
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<crate::models::AccountStatusCodeV1>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "mainRole", skip_serializing_if = "Option::is_none")]
    pub main_role: Option<crate::models::MainRoleV1>,
}

impl LoanAccountV1 {
    pub fn new() -> LoanAccountV1 {
        LoanAccountV1 {
            available_amount: None,
            balance: None,
            negated_balance: None,
            granted_amount: None,
            is_payment_from_this_account_allowed: None,
            is_standing_order_from_this_account_allowed: None,
            is_this_account_accessible: None,
            is_transfer_from_this_account_allowed: None,
            is_transfer_to_this_account_allowed: None,
            number: None,
            owner: None,
            account_product: None,
            status_code: None,
            title: None,
            account_id: None,
            main_role: None,
        }
    }
}


