/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailboxAttachment {
    #[serde(rename = "attachmentId")]
    pub attachment_id: i32,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "attachment", skip_serializing_if = "Option::is_none")]
    pub attachment: Option<String>,
}

impl MailboxAttachment {
    pub fn new(attachment_id: i32) -> MailboxAttachment {
        MailboxAttachment {
            attachment_id,
            name: None,
            attachment: None,
        }
    }
}


