/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MainRoleV1 {
    #[serde(rename = "Owner")]
    Owner,
    #[serde(rename = "Disposal")]
    Disposal,
    #[serde(rename = "CoOwner")]
    CoOwner,
    #[serde(rename = "CoDebtor")]
    CoDebtor,
    #[serde(rename = "Collateral")]
    Collateral,
    #[serde(rename = "Guardian")]
    Guardian,
    #[serde(rename = "Access")]
    Access,
    #[serde(rename = "Addressee")]
    Addressee,
    #[serde(rename = "Guarantator")]
    Guarantator,
    #[serde(rename = "Undefined")]
    Undefined,

}

impl ToString for MainRoleV1 {
    fn to_string(&self) -> String {
        match self {
            Self::Owner => String::from("Owner"),
            Self::Disposal => String::from("Disposal"),
            Self::CoOwner => String::from("CoOwner"),
            Self::CoDebtor => String::from("CoDebtor"),
            Self::Collateral => String::from("Collateral"),
            Self::Guardian => String::from("Guardian"),
            Self::Access => String::from("Access"),
            Self::Addressee => String::from("Addressee"),
            Self::Guarantator => String::from("Guarantator"),
            Self::Undefined => String::from("Undefined"),
        }
    }
}




