/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageItem {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<crate::models::Category>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::Status>,
    #[serde(rename = "flag")]
    pub flag: i32,
    #[serde(rename = "receivedDate")]
    pub received_date: String,
    #[serde(rename = "attachmentId", skip_serializing_if = "Option::is_none")]
    pub attachment_id: Option<i32>,
    #[serde(rename = "linkName", skip_serializing_if = "Option::is_none")]
    pub link_name: Option<String>,
    #[serde(rename = "linkUrl", skip_serializing_if = "Option::is_none")]
    pub link_url: Option<String>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
}

impl MessageItem {
    pub fn new(id: i64, flag: i32, received_date: String) -> MessageItem {
        MessageItem {
            id,
            subject: None,
            category: None,
            source: None,
            status: None,
            flag,
            received_date,
            attachment_id: None,
            link_name: None,
            link_url: None,
            body: None,
        }
    }
}


