/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NewStatusType : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NewStatusType {
    #[serde(rename = "Stopped")]
    Stopped,
    #[serde(rename = "Reactivated")]
    Reactivated,
    #[serde(rename = "IgnoreLimit")]
    IgnoreLimit,

}

impl ToString for NewStatusType {
    fn to_string(&self) -> String {
        match self {
            Self::Stopped => String::from("Stopped"),
            Self::Reactivated => String::from("Reactivated"),
            Self::IgnoreLimit => String::from("IgnoreLimit"),
        }
    }
}




