/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NewStatusTypeV1 {
    #[serde(rename = "Stopped")]
    Stopped,
    #[serde(rename = "Reactivated")]
    Reactivated,
    #[serde(rename = "IgnoreLimit")]
    IgnoreLimit,

}

impl ToString for NewStatusTypeV1 {
    fn to_string(&self) -> String {
        match self {
            Self::Stopped => String::from("Stopped"),
            Self::Reactivated => String::from("Reactivated"),
            Self::IgnoreLimit => String::from("IgnoreLimit"),
        }
    }
}




