/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Payment {
    #[serde(rename = "paymentId", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<String>,
    #[serde(rename = "recipientAccountNumber", skip_serializing_if = "Option::is_none")]
    pub recipient_account_number: Option<String>,
    #[serde(rename = "amount")]
    pub amount: f32,
    #[serde(rename = "dueDate")]
    pub due_date: String,
    #[serde(rename = "kid", skip_serializing_if = "Option::is_none")]
    pub kid: Option<String>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "allowedNewStatusTypes", skip_serializing_if = "Option::is_none")]
    pub allowed_new_status_types: Option<Vec<crate::models::NewStatusType>>,
    #[serde(rename = "statusDetails", skip_serializing_if = "Option::is_none")]
    pub status_details: Option<String>,
    #[serde(rename = "productType", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<String>,
    #[serde(rename = "paymentType", skip_serializing_if = "Option::is_none")]
    pub payment_type: Option<String>,
    #[serde(rename = "paymentNumber")]
    pub payment_number: i32,
    #[serde(rename = "beneficiaryName", skip_serializing_if = "Option::is_none")]
    pub beneficiary_name: Option<String>,
}

impl Payment {
    pub fn new(amount: f32, due_date: String, is_active: bool, payment_number: i32) -> Payment {
        Payment {
            payment_id: None,
            recipient_account_number: None,
            amount,
            due_date,
            kid: None,
            text: None,
            is_active,
            status: None,
            allowed_new_status_types: None,
            status_details: None,
            product_type: None,
            payment_type: None,
            payment_number,
            beneficiary_name: None,
        }
    }
}


