/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum ProductCodeV1 {
    #[serde(rename = "DebitCard")]
    DebitCard,
    #[serde(rename = "DebitCardCL")]
    DebitCardCL,
    #[serde(rename = "CreditCard")]
    CreditCard,
    #[serde(rename = "CreditCardCL")]
    CreditCardCL,
    #[serde(rename = "DebitCardYouth")]
    DebitCardYouth,
    #[serde(rename = "DebitCardYouthCL")]
    DebitCardYouthCL,
    #[serde(rename = "X2XCard")]
    X2XCard,
    #[serde(rename = "X2XCardChild")]
    X2XCardChild,
    #[serde(rename = "X2XCardChildNet")]
    X2XCardChildNet,
    #[serde(rename = "ElectronCard")]
    ElectronCard,
    #[serde(rename = "Unknown")]
    Unknown,

}

impl std::string::ToString for ProductCodeV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::DebitCard => "DebitCard".to_string(),
        
            Self::DebitCardCL => "DebitCardCL".to_string(),
        
            Self::CreditCard => "CreditCard".to_string(),
        
            Self::CreditCardCL => "CreditCardCL".to_string(),
        
            Self::DebitCardYouth => "DebitCardYouth".to_string(),
        
            Self::DebitCardYouthCL => "DebitCardYouthCL".to_string(),
        
            Self::X2XCard => "X2XCard".to_string(),
        
            Self::X2XCardChild => "X2XCardChild".to_string(),
        
            Self::X2XCardChildNet => "X2XCardChildNet".to_string(),
        
            Self::ElectronCard => "ElectronCard".to_string(),
        
            Self::Unknown => "Unknown".to_string(),
        
        }
    }
}





