/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum RelationshipStatusV1 {
    #[serde(rename = "Single")]
    Single,
    #[serde(rename = "Married")]
    Married,
    #[serde(rename = "CoHabitant")]
    CoHabitant,
    #[serde(rename = "Separated")]
    Separated,
    #[serde(rename = "Widow")]
    Widow,

}

impl std::string::ToString for RelationshipStatusV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::Single => "Single".to_string(),
        
            Self::Married => "Married".to_string(),
        
            Self::CoHabitant => "CoHabitant".to_string(),
        
            Self::Separated => "Separated".to_string(),
        
            Self::Widow => "Widow".to_string(),
        
        }
    }
}





