/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RelationshipStatusV1 {
    #[serde(rename = "Single")]
    Single,
    #[serde(rename = "Married")]
    Married,
    #[serde(rename = "CoHabitant")]
    CoHabitant,
    #[serde(rename = "Separated")]
    Separated,
    #[serde(rename = "Widow")]
    Widow,

}

impl ToString for RelationshipStatusV1 {
    fn to_string(&self) -> String {
        match self {
            Self::Single => String::from("Single"),
            Self::Married => String::from("Married"),
            Self::CoHabitant => String::from("CoHabitant"),
            Self::Separated => String::from("Separated"),
            Self::Widow => String::from("Widow"),
        }
    }
}




