/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum ReservationTypeV1 {
    #[serde(rename = "NotReservation")]
    NotReservation,
    #[serde(rename = "VisaReservation")]
    VisaReservation,
    #[serde(rename = "PurchaseReservation")]
    PurchaseReservation,
    #[serde(rename = "AtmReservation")]
    AtmReservation,

}

impl std::string::ToString for ReservationTypeV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::NotReservation => "NotReservation".to_string(),
        
            Self::VisaReservation => "VisaReservation".to_string(),
        
            Self::PurchaseReservation => "PurchaseReservation".to_string(),
        
            Self::AtmReservation => "AtmReservation".to_string(),
        
        }
    }
}





