/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReservationTypeV1 {
    #[serde(rename = "NotReservation")]
    NotReservation,
    #[serde(rename = "VisaReservation")]
    VisaReservation,
    #[serde(rename = "PurchaseReservation")]
    PurchaseReservation,
    #[serde(rename = "AtmReservation")]
    AtmReservation,

}

impl ToString for ReservationTypeV1 {
    fn to_string(&self) -> String {
        match self {
            Self::NotReservation => String::from("NotReservation"),
            Self::VisaReservation => String::from("VisaReservation"),
            Self::PurchaseReservation => String::from("PurchaseReservation"),
            Self::AtmReservation => String::from("AtmReservation"),
        }
    }
}




