/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SalaryFrequencyV1 {
    #[serde(rename = "Monthly")]
    Monthly,
    #[serde(rename = "BiWeekly")]
    BiWeekly,

}

impl ToString for SalaryFrequencyV1 {
    fn to_string(&self) -> String {
        match self {
            Self::Monthly => String::from("Monthly"),
            Self::BiWeekly => String::from("BiWeekly"),
        }
    }
}




