/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum SalaryFrequencyV1 {
    #[serde(rename = "Monthly")]
    Monthly,
    #[serde(rename = "BiWeekly")]
    BiWeekly,

}

impl std::string::ToString for SalaryFrequencyV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::Monthly => "Monthly".to_string(),
        
            Self::BiWeekly => "BiWeekly".to_string(),
        
        }
    }
}





