/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SourceType : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SourceType {
    #[serde(rename = "AccountStatement")]
    AccountStatement,
    #[serde(rename = "Archive")]
    Archive,

}

impl ToString for SourceType {
    fn to_string(&self) -> String {
        match self {
            Self::AccountStatement => String::from("AccountStatement"),
            Self::Archive => String::from("Archive"),
        }
    }
}




