/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SourceTypeV1 {
    #[serde(rename = "AccountStatement")]
    AccountStatement,
    #[serde(rename = "Archive")]
    Archive,

}

impl ToString for SourceTypeV1 {
    fn to_string(&self) -> String {
        match self {
            Self::AccountStatement => String::from("AccountStatement"),
            Self::Archive => String::from("Archive"),
        }
    }
}




