/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum SourceTypeV1 {
    #[serde(rename = "AccountStatement")]
    AccountStatement,
    #[serde(rename = "Archive")]
    Archive,

}

impl std::string::ToString for SourceTypeV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::AccountStatement => "AccountStatement".to_string(),
        
            Self::Archive => "Archive".to_string(),
        
        }
    }
}





