/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum StandingOrderTypeV1 {
    #[serde(rename = "Payment")]
    Payment,
    #[serde(rename = "Transfer")]
    Transfer,
    #[serde(rename = "Other")]
    Other,

}

impl std::string::ToString for StandingOrderTypeV1 {
    fn to_string(&self) -> String {
        match self {
        
            Self::Payment => "Payment".to_string(),
        
            Self::Transfer => "Transfer".to_string(),
        
            Self::Other => "Other".to_string(),
        
        }
    }
}





