/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StandingOrderType : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StandingOrderType {
    #[serde(rename = "Payment")]
    Payment,
    #[serde(rename = "Transfer")]
    Transfer,
    #[serde(rename = "Other")]
    Other,

}

impl ToString for StandingOrderType {
    fn to_string(&self) -> String {
        match self {
            Self::Payment => String::from("Payment"),
            Self::Transfer => String::from("Transfer"),
            Self::Other => String::from("Other"),
        }
    }
}




