/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StandingOrderFrequencyV1 {
    #[serde(rename = "Other")]
    Other,
    #[serde(rename = "Weekly")]
    Weekly,
    #[serde(rename = "Biweekly")]
    Biweekly,
    #[serde(rename = "Semimonthly")]
    Semimonthly,
    #[serde(rename = "Monthly")]
    Monthly,
    #[serde(rename = "Bimonthly")]
    Bimonthly,
    #[serde(rename = "Quarterly")]
    Quarterly,
    #[serde(rename = "Yearly")]
    Yearly,
    #[serde(rename = "Daily")]
    Daily,

}

impl ToString for StandingOrderFrequencyV1 {
    fn to_string(&self) -> String {
        match self {
            Self::Other => String::from("Other"),
            Self::Weekly => String::from("Weekly"),
            Self::Biweekly => String::from("Biweekly"),
            Self::Semimonthly => String::from("Semimonthly"),
            Self::Monthly => String::from("Monthly"),
            Self::Bimonthly => String::from("Bimonthly"),
            Self::Quarterly => String::from("Quarterly"),
            Self::Yearly => String::from("Yearly"),
            Self::Daily => String::from("Daily"),
        }
    }
}




