/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use serde::{Deserialize, Serialize};



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct StandingOrderV1 {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    #[serde(rename = "beneficiaryName", skip_serializing_if = "Option::is_none")]
    pub beneficiary_name: Option<String>,
    #[serde(rename = "cId", skip_serializing_if = "Option::is_none")]
    pub c_id: Option<String>,
    #[serde(rename = "creditAccountNumber", skip_serializing_if = "Option::is_none")]
    pub credit_account_number: Option<String>,
    #[serde(rename = "debitAccountNumber", skip_serializing_if = "Option::is_none")]
    pub debit_account_number: Option<String>,
    #[serde(rename = "freeTerms", skip_serializing_if = "Option::is_none")]
    pub free_terms: Option<Vec<String>>,
    #[serde(rename = "frequency", skip_serializing_if = "Option::is_none")]
    pub frequency: Option<crate::models::StandingOrderFrequencyV1>,
    #[serde(rename = "lastPaymentDate", skip_serializing_if = "Option::is_none")]
    pub last_payment_date: Option<String>,
    #[serde(rename = "nextDueDate", skip_serializing_if = "Option::is_none")]
    pub next_due_date: Option<String>,
    #[serde(rename = "standingOrderEndDate", skip_serializing_if = "Option::is_none")]
    pub standing_order_end_date: Option<String>,
    #[serde(rename = "standingOrderId", skip_serializing_if = "Option::is_none")]
    pub standing_order_id: Option<i32>,
    #[serde(rename = "standingOrderStartDate", skip_serializing_if = "Option::is_none")]
    pub standing_order_start_date: Option<String>,
    #[serde(rename = "standingOrderType", skip_serializing_if = "Option::is_none")]
    pub standing_order_type: Option<crate::models::StandingOrderTypeV1>,
}

impl StandingOrderV1 {
    pub fn new() -> StandingOrderV1 {
        StandingOrderV1 {
            amount: None,
            beneficiary_name: None,
            c_id: None,
            credit_account_number: None,
            debit_account_number: None,
            free_terms: None,
            frequency: None,
            last_payment_date: None,
            next_due_date: None,
            standing_order_end_date: None,
            standing_order_id: None,
            standing_order_start_date: None,
            standing_order_type: None,
        }
    }
}


