/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandingOrder {
    #[serde(rename = "amount")]
    pub amount: f32,
    #[serde(rename = "beneficiaryName", skip_serializing_if = "Option::is_none")]
    pub beneficiary_name: Option<String>,
    #[serde(rename = "cId", skip_serializing_if = "Option::is_none")]
    pub c_id: Option<String>,
    #[serde(rename = "creditAccountNumber", skip_serializing_if = "Option::is_none")]
    pub credit_account_number: Option<String>,
    #[serde(rename = "debitAccountNumber", skip_serializing_if = "Option::is_none")]
    pub debit_account_number: Option<String>,
    #[serde(rename = "freeTerms", skip_serializing_if = "Option::is_none")]
    pub free_terms: Option<Vec<String>>,
    #[serde(rename = "frequency")]
    pub frequency: crate::models::StandingOrderFrequency,
    #[serde(rename = "lastPaymentDate", skip_serializing_if = "Option::is_none")]
    pub last_payment_date: Option<String>,
    #[serde(rename = "nextDueDate", skip_serializing_if = "Option::is_none")]
    pub next_due_date: Option<String>,
    #[serde(rename = "standingOrderEndDate", skip_serializing_if = "Option::is_none")]
    pub standing_order_end_date: Option<String>,
    #[serde(rename = "standingOrderId")]
    pub standing_order_id: i32,
    #[serde(rename = "standingOrderStartDate", skip_serializing_if = "Option::is_none")]
    pub standing_order_start_date: Option<String>,
    #[serde(rename = "standingOrderType")]
    pub standing_order_type: crate::models::StandingOrderType,
}

impl StandingOrder {
    pub fn new(amount: f32, frequency: crate::models::StandingOrderFrequency, standing_order_id: i32, standing_order_type: crate::models::StandingOrderType) -> StandingOrder {
        StandingOrder {
            amount,
            beneficiary_name: None,
            c_id: None,
            credit_account_number: None,
            debit_account_number: None,
            free_terms: None,
            frequency,
            last_payment_date: None,
            next_due_date: None,
            standing_order_end_date: None,
            standing_order_id,
            standing_order_start_date: None,
            standing_order_type,
        }
    }
}


