/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StandingOrderTypeV1 {
    #[serde(rename = "Payment")]
    Payment,
    #[serde(rename = "Transfer")]
    Transfer,
    #[serde(rename = "Other")]
    Other,

}

impl ToString for StandingOrderTypeV1 {
    fn to_string(&self) -> String {
        match self {
            Self::Payment => String::from("Payment"),
            Self::Transfer => String::from("Transfer"),
            Self::Other => String::from("Other"),
        }
    }
}




