/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Status : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Unread")]
    Unread,
    #[serde(rename = "Read")]
    Read,

}

impl ToString for Status {
    fn to_string(&self) -> String {
        match self {
            Self::Unread => String::from("Unread"),
            Self::Read => String::from("Read"),
        }
    }
}




