/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferCreateRequestV1 {
    #[serde(rename = "fromAccountId", skip_serializing_if = "Option::is_none")]
    pub from_account_id: Option<String>,
    #[serde(rename = "toAccountId", skip_serializing_if = "Option::is_none")]
    pub to_account_id: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
}

impl TransferCreateRequestV1 {
    pub fn new() -> TransferCreateRequestV1 {
        TransferCreateRequestV1 {
            from_account_id: None,
            to_account_id: None,
            message: None,
            amount: None,
        }
    }
}


