/*
 * SBanken API
 *
 * API for accessing bank information in SBanken
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionDetailV1 {
    #[serde(rename = "formattedAccountNumber", skip_serializing_if = "Option::is_none")]
    pub formatted_account_number: Option<String>,
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<i64>,
    #[serde(rename = "cid", skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
    #[serde(rename = "amountDescription", skip_serializing_if = "Option::is_none")]
    pub amount_description: Option<String>,
    #[serde(rename = "receiverName", skip_serializing_if = "Option::is_none")]
    pub receiver_name: Option<String>,
    #[serde(rename = "numericReference", skip_serializing_if = "Option::is_none")]
    pub numeric_reference: Option<i64>,
    #[serde(rename = "payerName", skip_serializing_if = "Option::is_none")]
    pub payer_name: Option<String>,
    #[serde(rename = "registrationDate", skip_serializing_if = "Option::is_none")]
    pub registration_date: Option<String>,
}

impl TransactionDetailV1 {
    pub fn new() -> TransactionDetailV1 {
        TransactionDetailV1 {
            formatted_account_number: None,
            transaction_id: None,
            cid: None,
            amount_description: None,
            receiver_name: None,
            numeric_reference: None,
            payer_name: None,
            registration_date: None,
        }
    }
}


