/*
 * Bff.ApiBeta : V2 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferCreateRequest {
    #[serde(rename = "fromAccountId")]
    pub from_account_id: String,
    #[serde(rename = "toAccountId")]
    pub to_account_id: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "amount")]
    pub amount: f32,
}

impl TransferCreateRequest {
    pub fn new(from_account_id: String, to_account_id: String, message: String, amount: f32) -> TransferCreateRequest {
        TransferCreateRequest {
            from_account_id,
            to_account_id,
            message,
            amount,
        }
    }
}


